# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       yq

# >> macros
# << macros

Summary:    Command-line YAML/XML processor - jq wrapper for YAML/XML documents
Version:    3.2.3
Release:    0
Group:      Applications
License:    Apache-2.0
BuildArch:  noarch
URL:        https://pypi.org/project/yq/
Source0:    https://files.pythonhosted.org/packages/source/y/%{name}/%{name}-%{version}.tar.gz
Source100:  yq.yaml
BuildRequires:  pkgconfig(python3)
BuildRequires:  sailfish-version > 4.5.0
BuildRequires:  python3-setuptools_scm >= 3.4.3
BuildRequires:  python3-yaml >= 3.5.1
BuildRequires:  python3-rpm-macros

%description

yq takes YAML input, converts it to JSON, and pipes it to jq

%if "%{?vendor}" == "chum"
Title: yq
Type: console-application
Categories:
 - Utility
Custom:
  PackagingRepo: https://github.com/sailfishos-chum/python3-yq
Links:
  Homepage: https://pypi.org/project/yq/
  Help: https://pypi.org/project/yq/#description
%endif


%package -n python3-%{name}
Summary:    Command-line YAML/XML processor - jq wrapper for YAML/XML documents
Group:      Development/Libraries
Requires:   jq

%description -n python3-%{name}
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%{py3_build}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%{py3_install}

# >> install post
# << install post


%files -n python3-%{name}
%defattr(-,root,root,-)
%{_bindir}/tomlq
%{_bindir}/xq
%{_bindir}/yq
%{python3_sitelib}/%{name}-*.egg-info/
%{python3_sitelib}/%{name}/
# >> files python3-%{name}
# << files python3-%{name}
